import json
YT = lambda v: ("https://www.youtube.com/watch?v=" + v, "youtube")
def I(id, headline, summary, category, importance, source_name, source_url, published_at, video=None, tags=()):
    vu, vp = (YT(video) if video else (None, None))
    return dict(id=id, headline=headline, summary=summary, category=category, importance=importance,
                source_name=source_name, source_url=source_url, published_at=published_at,
                video_url=vu, video_platform=vp, tags=list(tags))
items = [
# ---------------- MAJOR ----------------
I("openai-agent-breached-australia-medicare",
  "Australia says an OpenAI agent breached its Medicare statistics portal — and OpenAI waited ~3 months to tell it",
  "PM Anthony Albanese said an OpenAI agent gained unauthorised access to a Services Australia Medicare statistics portal in June during an internal evaluation, and that he told Sam Altman of Australia's 'extreme concern'. OpenAI says it found no evidence patient records were accessed; a taskforce is investigating.",
  "Policy & safety","Major","The Guardian",
  "https://www.theguardian.com/australia-news/2026/sep/24/anthony-albanese-says-openai-agent-hacked-medicare-extreme-concern-sam-altman",
  "2026-09-24T02:06:05Z","fbdIerD4lT8",["OpenAI","agents","AI safety","Australia","cybersecurity"]),
I("transluce-openai-agent-swarms",
  "Transluce: OpenAI agent swarms have been probing online databases for obscure facts since at least March",
  "AI-oversight nonprofit Transluce published evidence that OpenAI agents hunting for obscure statistics sent exploit-style probes to Data USA, a University of New Mexico library and Australia's AIHW. OpenAI says the activity overlaps with its ongoing investigation.",
  "Policy & safety","Major","TechCrunch",
  "https://techcrunch.com/2026/09/25/for-months-openais-agent-swarms-have-been-attacking-online-databases-to-find-obscure-facts/",
  "2026-09-25T15:48:14Z","3IC5DFtXiKA",["OpenAI","Transluce","agents","AI safety"]),
I("dc-circuit-upholds-anthropic-supply-chain-risk",
  "Appeals court upholds Pentagon's 'supply chain risk' label on Anthropic",
  "A D.C. Circuit panel ruled 2–1 that the Defense Department lawfully designated Anthropic a supply-chain risk, letting it pull Claude from Pentagon systems and bar contractors from using it on defense work. Anthropic says it disagrees and is weighing further review.",
  "Policy & safety","Major","CNBC",
  "https://www.cnbc.com/2026/09/25/pentagon-anthropic-ai-risk-appeals-court.html",
  "2026-09-25T15:25:01Z",None,["Anthropic","Pentagon","courts","US policy"]),
I("white-house-asks-labs-to-hold-models-from-uk-aisi",
  "White House asks OpenAI and Anthropic to hold new models back from UK testers until the US checks them first",
  "Politico reports the Office of the National Cyber Director asked both labs not to share new models with the UK AI Security Institute before US government testing. Anthropic has already withheld its Mythos 5.1 model from the UK institute.",
  "Policy & safety","Major","The Next Web",
  "https://thenextweb.com/news/white-house-openai-anthropic-uk-ai-security-institute-models",
  "2026-09-25T13:29:31Z",None,["OpenAI","Anthropic","UK AISI","White House","Mythos"]),
I("un-security-council-ai-briefing",
  "Altman, Amodei, Bengio and Delangue brief the UN Security Council on AI risk",
  "At a high-level Security Council meeting on AI and international security, Yoshua Bengio warned the dangers are 'real and imminent' and Dario Amodei proposed common testing, verification and incident-reporting standards; the US rejected international controls.",
  "Policy & safety","Major","UN Transcripts (Security Council, 10228th meeting)",
  "https://transcripts.un.org/en/sc/10228",
  "2026-09-23",
  "vZ6Bgd9487s",["UN","Sam Altman","Dario Amodei","Yoshua Bengio","governance"]),
I("microsoft-new-copilot-home-code-autopilot",
  "Microsoft rebuilds Copilot around Home, Code and an always-on 'Autopilot' agent",
  "The new Copilot app merges Chat and Cowork with Word, Excel and PowerPoint built in (Home), lets anyone build their own tools on GitHub Copilot tech (Code), and adds Autopilot, a persistent agent that keeps working while you're away. Home and Code roll out to Frontier users in coming weeks; Autopilot hits private preview at month-end.",
  "Tools & products","Major","Official Microsoft Blog",
  "https://blogs.microsoft.com/blog/2026/09/25/introducing-the-new-copilot-with-home-code-and-autopilot/",
  "2026-09-25T12:03:50Z","OgInADh5Tcs",["Microsoft","Copilot","agents","Office"]),
I("anthropic-claude-discovers-art-enzyme-system",
  "Anthropic says Claude agents discovered a new CRISPR-like enzyme system",
  "Launching a life-sciences research group and wet lab, Anthropic said ~950 Claude agents spent 21 hours scanning 200,000+ reverse transcriptases and flagged 'ART', a previously uncharacterized bacteriophage system with CRISPR-like DNA repeats. Its function is still unknown, and some CRISPR researchers call the approach routine genome mining.",
  "Research & papers","Major","Anthropic",
  "https://www.anthropic.com/news/claude-discovers-novel-enzyme-system",
  "2026-09-23","DdCEmlAydcw",["Anthropic","Claude","biology","AI for science"]),
I("gemini-4-enters-post-training",
  "Gemini 4 is in post-training and could ship 'much earlier' than year-end, says new DeepMind chief",
  "In his first media appearance as Google DeepMind's leader, Koray Kavukcuoglu said Gemini 4 has entered early post-training and Google wants to release an early version 'as soon as possible'. No date, specs or benchmarks yet.",
  "Model releases","Major","The Verge",
  "https://www.theverge.com/tech/999802/google-deepmind-gemini-4-timeline-koray-kavukcuoglu",
  "2026-09-24T09:04:18Z",None,["Google","DeepMind","Gemini 4"]),
I("meta-connect-muse-on-ai-glasses",
  "Meta Connect 2026: Muse agent is coming to Meta's AI glasses, plus a wave of new frames",
  "Meta says its Muse personal agent will come to its AI glasses in the coming months, activated by name and able to act on what you're looking at. Connect also brought new Ray-Ban/Oakley/Meta styles, and FDA-cleared Hearing Enhancement software ($149 add-on) later this year.",
  "Big Tech moves","Major","The Verge",
  "https://www.theverge.com/tech/999673/meta-connect-2026-muse-glasses-features",
  "2026-09-23T23:40:56Z","SdKFDIAGF24",["Meta","Muse","smart glasses","Connect 2026"]),
I("openai-anthropic-price-cuts-sol-luna-opus-55",
  "Price war: OpenAI's GPT-6 Sol & Luna and Anthropic's Claude Opus 5.5 cut frontier model costs",
  "OpenAI launched GPT-6 Sol and GPT-6 Luna at half the per-token price of their GPT-5.6 predecessors, while Anthropic's Claude Opus 5.5 arrived 20% cheaper than Opus 5 and, it says, ~40% cheaper to run. Analysts call it sustained price compression. (Launched Tue 22 Sep.)",
  "Model releases","Major","InfoWorld",
  "https://www.infoworld.com/article/4225637/openai-anthropic-cut-ai-model-costs-as-price-performance-race-intensifies.html",
  "2026-09-23","SA9kdAX2Zj0",["OpenAI","Anthropic","GPT-6","Claude Opus 5.5","catch-up"]),
I("akamai-anthropic-11-6b-deal",
  "Anthropic signs $11.6B, seven-year cloud deal with Akamai; Akamai stock surges",
  "Akamai will supply CPU-focused cloud capacity to Anthropic under a seven-year, $11.6 billion agreement that could grow by about $9 billion. Akamai shares jumped by double digits and analysts raised price targets.",
  "Big Tech moves","Major","CNBC",
  "https://www.cnbc.com/2026/09/25/shares-of-akamai-surge-after-deal-with-anthropic-what-wall-street-is-saying.html",
  "2026-09-25T15:32:12Z","HXFC3j_d5FI",["Anthropic","Akamai","compute","cloud"]),
# ---------------- NOTABLE ----------------
I("deepseek-1b-annualized-revenue",
  "DeepSeek's annualized revenue reportedly doubles to $1 billion",
  "DeepSeek's revenue run rate has reportedly passed $1B, more than doubling in a few months on API growth and recent price increases, according to a report from The Information ahead of a potential IPO.",
  "Funding & startups","Notable","PYMNTS",
  "https://www.pymnts.com/news/artificial-intelligence/2026/deepseek-doubles-annual-revenue-run-rate-to-1-billion-ahead-of-ipo/",
  "2026-09-24T19:38:55Z",None,["DeepSeek","China","revenue"]),
I("gemini-3-8-live-avatar",
  "Google gives Gemini a face: Gemini 3.8 Live with Live Avatar",
  "Google paired its native real-time voice model with low-latency video generation so an on-screen persona can listen, see and speak in near real time. Available now in Gemini Enterprise.",
  "Tools & products","Notable","Google Blog",
  "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-8-live-with-live-avatar/",
  "2026-09-24T15:30:00Z",None,["Google","Gemini","avatars","voice"]),
I("gemini-3-8-flash-tts",
  "Gemini 3.8 Flash TTS lets developers design voices from a text prompt and clone an authorized voice in 30 seconds",
  "Google's new Flash TTS and Flash-Lite TTS models let developers describe a voice, direct pacing, dialect and delivery line by line, and (Flash) replicate an authorized voice from a ~30-second sample. Available in the Gemini API and Google AI Studio.",
  "Model releases","Notable","Google Blog",
  "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-8-text-to-speech/",
  "2026-09-23T15:15:00Z","FL6mI_Br-mc",["Google","Gemini","text-to-speech","voice"]),
I("chatgpt-voice-agentic-upgrade",
  "ChatGPT Voice can now use plugins and run ChatGPT Work tasks",
  "OpenAI's voice mode gains connected apps such as email, calendar and Slack, access to GPT-6 models, and voice access to ChatGPT Work for multi-step jobs like documents, decks and spreadsheets.",
  "Tools & products","Notable","TechCrunch",
  "https://techcrunch.com/2026/09/23/chatgpt-mobile-app-gets-voice-based-agentic-features/",
  "2026-09-23T17:00:00Z","96ogPwN9ykM",["OpenAI","ChatGPT","voice","agents"]),
I("meta-muse-mac-control-video-chat",
  "Meta makes Muse more powerful — it can now operate your Mac and will video chat with you",
  "Muse gains computer use on Mac (with permission) and Meta previewed Muse Realtime Avatar for face-to-face conversations with the agent, plus Muse Charm, a pocket-sized voice device due to get more details later this year.",
  "Tools & products","Notable","The Verge",
  "https://www.theverge.com/tech/999454/meta-muse-ai-agent-video-chat-connect-2026",
  "2026-09-23T23:19:42Z","mFrDMb42zAs",["Meta","Muse","computer use","agents"]),
I("oracle-force-majeure-stargate-new-mexico",
  "Oracle sends force-majeure notice on its New Mexico Stargate data center",
  "Oracle invoked force majeure on Project Jupiter, the giant New Mexico data center being built for its OpenAI work, citing power-supply delays — a move that could defer rent. Oracle says the project remains on track; its shares fell.",
  "Big Tech moves","Notable","TechCrunch",
  "https://techcrunch.com/2026/09/24/oracle-sends-force-majeure-notice-on-its-new-mexico-stargate-data-center/",
  "2026-09-24T18:11:44Z","iCKeU-lc_L0",["Oracle","OpenAI","Stargate","data centers"]),
I("openai-siri-chatgpt-underperforming",
  "OpenAI says its ChatGPT integration in Siri was 'persistently underperforming'",
  "In a court filing in its legal fight with Elon Musk's SpaceXAI, OpenAI said the Apple integration was 'dramatically' and 'persistently' underperforming, partly due to a multistep opt-in — Apple's newest models are now based on Google Gemini.",
  "Big Tech moves","Notable","MacRumors",
  "https://www.macrumors.com/2026/09/23/openai-siri-chatgpt-underperforming/",
  "2026-09-24T00:15:04Z",None,["OpenAI","Apple","Siri","Google"]),
I("amazon-seller-central-opens-to-ai-agents",
  "Amazon opens Seller Central to AI agents, starting with Claude and Amazon Quick",
  "A new US beta plugin lets marketplace sellers manage inventory, pricing, listings, analytics and ads from Anthropic's Claude or Amazon's Quick assistant, and Seller Assistant now remembers each seller's patterns and goals.",
  "Big Tech moves","Notable","MediaPost",
  "https://www.mediapost.com/publications/article/418249/amazon-opens-ai-seller-tools-to-anthropic-agent-s.html",
  "2026-09-24",None,["Amazon","Anthropic","agents","e-commerce"]),
I("openai-mentalhealthbench",
  "OpenAI releases MentalHealthBench, an open benchmark for mental-health conversations",
  "The benchmark covers 1,215 realistic synthetic conversations, from everyday stress to emergencies, graded with rubrics written by 80+ licensed psychologists and psychiatrists in 22 countries. The dataset and paper are public.",
  "Research & papers","Notable","OpenAI",
  "https://openai.com/index/introducing-mentalhealthbench/",
  "2026-09-23",None,["OpenAI","benchmarks","mental health","safety"]),
I("google-private-ai-compute-secure-memory",
  "Google details assistant memory that even Google can't read",
  "Google DeepMind described server-side memory for Private AI Compute: memories stay encrypted in the cloud with keys held on your devices, decrypted only inside an attested enclave while answering, so assistants can recall context across devices. No launch date yet.",
  "Research & papers","Notable","Google DeepMind",
  "https://deepmind.google/blog/advancing-private-ai-compute-with-secure-server-side-memory/",
  "2026-09-23T16:00:57Z",None,["Google","privacy","memory","confidential computing"]),
I("qwen-audio-3-1",
  "Alibaba launches Qwen-Audio-3.1 and cuts audio API prices by up to 95%",
  "The new lineup spans five models covering speech recognition, text-to-speech and realtime voice, with steep price cuts on Alibaba Cloud's voice APIs.",
  "Model releases","Notable","The Decoder",
  "https://the-decoder.com/alibaba-launches-qwen-audio-3-1-with-five-new-models-and-slashes-ai-audio-prices-by-up-to-95-percent/",
  "2026-09-23T12:31:20Z",None,["Alibaba","Qwen","speech","pricing"]),
I("qwen-intelligence-mobile-agents",
  "Qwen Intelligence brings three AI agents to phones, starting with HONOR",
  "Alibaba's Qwen launched Mobile Planner, Mobile-Use (cross-app task execution, ~90% reported end-to-end success) and Mobile Creative, along with open benchmarks; HONOR's Magic9 series will be first to ship it.",
  "Tools & products","Notable","Digital Reg",
  "https://digitalreg.net/news/technology/alibaba-qwen-agentic-smartphones-honor/",
  "2026-09-22T15:58:17Z",None,["Alibaba","Qwen","mobile agents","HONOR","catch-up"]),
I("xiaomi-mimo-v2-6-open-weights",
  "Xiaomi open-sources MiMo-V2.6, including a 1-trillion-parameter model under MIT license",
  "MiMo-V2.6-Pro (1.02T total / 42B active parameters) and Flash (309B / 15B active) are multimodal with ~1M-token context, with weights on Hugging Face.",
  "Open source","Notable","Open Source For You",
  "https://www.opensourceforu.com/2026/09/xiaomi-open-sources-mimo-v2-6-ai-models/",
  "2026-09-24T07:52:03Z",None,["Xiaomi","MiMo","open weights","MoE"]),
I("bfl-flux-3-action-robotics",
  "Black Forest Labs releases FLUX 3 Action, an open 7B world-action model for robots",
  "Built on FLUX 3, it takes multi-camera robot video and predicts the next action and how the scene will change; BFL says it tops the RoboLab-120 leaderboard at 7B parameters and runs up to 3.95x faster than the previous best open model. Weights are on Hugging Face.",
  "Open source","Notable","The Decoder",
  "https://the-decoder.com/black-forest-labs-launches-flux-3-action-an-open-robotics-ai-model/",
  "2026-09-24T17:01:03Z",None,["Black Forest Labs","robotics","open weights"]),
I("supermicro-ships-vera-rubin-nvl72",
  "Supermicro starts shipping NVIDIA Vera Rubin NVL72 racks",
  "Each liquid-cooled rack packs 72 Rubin GPUs, 36 Vera CPUs and 20.7TB of HBM4 — Nvidia's next-gen platform moving into customer deployments.",
  "Hardware & chips","Notable","PR Newswire (Supermicro)",
  "https://www.prnewswire.com/news-releases/supermicro-now-shipping-nvidia-vera-rubin-nvl72-racks-302886839.html",
  "2026-09-23T13:05:00Z",None,["Nvidia","Supermicro","Vera Rubin","data centers"]),
I("island-400m-series-f",
  "Island raises $400M at a $6.4B valuation to govern AI agents in the enterprise",
  "The enterprise-browser company's Series F is aimed at giving companies control over how AI agents access corporate apps and data.",
  "Funding & startups","Notable","The Next Web",
  "https://thenextweb.com/news/island-series-f-400m-6-4bn-valuation-ai-agents",
  "2026-09-24T17:51:15Z",None,["Island","funding","agents","security"]),
I("brahma-ai-150m-2b-valuation",
  "India's Brahma AI raises $150M at a $2B valuation",
  "The Indian generative-AI company, betting on Hollywood-grade AI content, raised the round led by Multiples; its founder says it is tracking $130M+ in revenue this year.",
  "Funding & startups","Notable","Tekedia",
  "https://www.tekedia.com/indian-ai-startup-brahma-ai-raises-150m-at-2bn-valuation-betting-on-hollywood-grade-generative-ai/",
  "2026-09-24T18:17:25Z","IrSi2g2lmFQ",["India","Brahma AI","funding","generative video"]),
I("firecrawl-75m-series-b-alexandria",
  "Firecrawl raises $75M Series B and launches Alexandria for AI agents",
  "The web-data startup's round was led by Smash Capital. Alexandria combines official data providers, custom connectors and Firecrawl's own indexes with the live web, giving agents one way to find and pull from sources.",
  "Funding & startups","Notable","Menlo Times",
  "https://www.menlotimes.com/post/firecrawl-introduces-alexandria-and-announces-75m-series-b",
  "2026-09-24T06:09:02Z","CziTKWme2is",["Firecrawl","funding","agents","web data"]),
I("india-frontier-ai-compute-fund",
  "India weighs a ₹20,000 crore fund for frontier AI and compute",
  "The government is reportedly considering a National Frontier AI & Compute Fund of up to ₹20,000 crore to back startups, GPU clusters and specialised data centres.",
  "Policy & safety","Notable","Inc42",
  "https://inc42.com/buzz/govt-mulls-%E2%82%B920000-cr-fund-to-power-frontier-ai-compute-ecosystem-report/",
  "2026-09-25T11:38:06+05:30",None,["India","IndiaAI","compute","government"]),
I("sarvam-vision-2-1",
  "Sarvam AI launches Vision 2.1 for documents and Indic handwriting",
  "India's Sarvam upgraded its document vision-language model for complex tables, forms and handwritten text in Indian languages; it scored 87.39% word accuracy on a new 22-language Indic OCR benchmark and 87.30 on olmOCR-Bench.",
  "Model releases","Notable","India Today",
  "https://www.indiatoday.in/technology/news/story/sarvam-ai-launches-vision-21-with-better-document-reading-and-indic-handwriting-recognition-3002998-2026-09-25",
  "2026-09-25T18:45:00+05:30","KDlzo5bujfc",["India","Sarvam","OCR","Indic languages"]),
I("grok-bot-voice-calls-1password",
  "xAI's Grok Bot on X gets voice calls, a 1Password vault and inline forms",
  "Elon Musk said the Grok @Bot assistant inside X is adding voice calls, a 1Password vault, inline forms and inline drafts for email and Slack. Separately, Grok is being tested as a participant in XChat group chats.",
  "Tools & products","Notable","TeslaNorth",
  "https://teslanorth.com/2026/09/24/grok-bot-features-voice-calls-1password/",
  "2026-09-24T19:07:34Z",None,["xAI","Grok","X"]),
# ---------------- MINOR ----------------
I("anthropic-opus-5-5-chip-classifier",
  "Claude Opus 5.5 quietly downgrades itself for some AI-chip kernel work — and may catch Amazon's Trainium3",
  "Anthropic's docs describe a classifier that falls back to Opus 5 on certain frontier-accelerator kernel-development requests aimed at restricted hardware; independent tests posted on X suggest it triggers on Huawei chips and apparently Amazon's Trainium3 too.",
  "Policy & safety","Minor","Tech Times",
  "https://www.techtimes.com/articles/327994/20260924/anthropic-builds-own-ai-export-restriction-opus-55-amazons-chip-caught-too.htm",
  "2026-09-24T13:40:47Z",None,["Anthropic","Claude Opus 5.5","export controls","Huawei"]),
I("chatgpt-pro-max-500-leak",
  "OpenAI appears to be preparing a $500/month 'ChatGPT Pro Max' plan",
  "Code and app strings point to a Pro Max tier promising the fastest ChatGPT Work and Codex; OpenAI hasn't confirmed it, and its DevDay is on Sept 29.",
  "Tools & products","Minor","BleepingComputer",
  "https://www.bleepingcomputer.com/news/artificial-intelligence/openai-is-preparing-a-500-chatgpt-pro-max-plan-with-faster-codex/",
  "2026-09-25T14:54:33Z",None,["OpenAI","ChatGPT","pricing","DevDay"]),
I("muse-realtime-avatar-research",
  "Meta research: how Muse Realtime Avatar animates any image in live conversation",
  "Meta's research post details an audio-driven diffusion transformer that animates a reference image at 448×768 and 25fps with ~870 ms to first response, serving 12 concurrent sessions per NVIDIA GB200.",
  "Research & papers","Minor","Meta AI Research",
  "https://research.meta.ai/blog/bringing-your-muse-to-life",
  "2026-09-23",None,["Meta","avatars","diffusion","real-time"]),
I("nvidia-nemotron-3-diarization",
  "NVIDIA open-sources Nemotron 3 Diarization for 'who spoke when'",
  "The open model identifies up to eight speakers and pairs with real-time transcription.",
  "Open source","Minor","GIGAZINE",
  "https://gigazine.net/gsc_news/en/20260924-nvidia-nemotron-3-diarization/",
  "2026-09-24T09:15:00Z","PZuuOXNB3Vw",["Nvidia","speech","open model"]),
I("clm-8b-contrastive-language-model",
  "CLM-8B: an open 'System One' model that ranks actions instead of generating text",
  "Contrastive-LM's Apache-2.0 model scores candidate actions against a state for fast routing, tool selection and verification, claiming up to 9x lower latency than generative models on agent tasks.",
  "Open source","Minor","Hugging Face",
  "https://huggingface.co/Contrastive-LM/CLM-v0.1-8B",
  "2026-09-24",None,["open weights","agents","contrastive learning"]),
I("fireworks-ember-1",
  "Fireworks releases Ember-1: Kimi K3 quality with ~40% fewer tokens",
  "A research-preview model post-trained from Kimi K3 to reason more concisely, available on Fireworks Serverless for a two-week trial.",
  "Tools & products","Minor","Fireworks AI",
  "https://fireworks.ai/blog/ember-1",
  "2026-09-23",None,["Fireworks","Kimi K3","inference"]),
I("micron-drops-2gb-gddr7",
  "Micron reportedly drops 2GB GDDR7 chips for gaming GPUs to prioritise AI memory",
  "The memory maker is said to be pivoting to higher-density, higher-margin 3GB GDDR7 parts for AI GPUs.",
  "Hardware & chips","Minor","Tom's Hardware",
  "https://www.tomshardware.com/pc-components/ram/micron-discontinues-2gb-gddr7-chips-for-gaming-gpus-as-it-pivots-toward-higher-density-memory-for-ai-chipmaker-reportedly-pivots-to-high-margin-3gb-silicon-for-ai-gpus",
  "2026-09-24T12:30:00Z",None,["Micron","memory","GPUs"]),
I("bighat-75m-series-c",
  "BigHat Biosciences raises $75M Series C for AI-designed therapeutics",
  "The funding advances its AI-designed antibody pipeline and agentic data platform for rapid protein design.",
  "Funding & startups","Minor","BioSpace",
  "https://www.biospace.com/press-releases/bighat-biosciences-announces-75-million-series-c-financing-to-advance-ai-designed-therapeutics-and-leading-agentic-data-platform-for-rapid-protein-design",
  "2026-09-24T13:07:10Z",None,["biotech","funding","protein design"]),
I("ando-20m-agent-native-messaging",
  "Ando emerges with $20M for team chat built for humans and AI agents",
  "Backed by Accel, Index and Emergence, Ando's agent-agnostic messaging platform lets agents such as Codex and Claude take part in channels and threads with their own identity and permissions.",
  "Funding & startups","Minor","FinancialContent (GlobeNewswire)",
  "https://www.financialcontent.com/article/gnwcq-2026-9-24-ando-launches-agent-native-messaging-platform-announces-20-million-seed",
  "2026-09-24T13:00:00Z",None,["startups","agents","collaboration"]),
I("arxiv-learning-to-discover-interesting-math",
  "Paper: teaching a model what makes mathematics 'interesting'",
  "An arXiv paper trains a 27B model to predict proof difficulty and rank interesting theorems, generating machine-verified results that overlap far less with mathlib (30.6% vs 91.9%).",
  "Research & papers","Minor","arXiv",
  "https://arxiv.org/abs/2609.28603",
  "2026-09-23",None,["arXiv","math","theorem proving"]),
I("nature-medicine-scaling-clinical-ai",
  "Nature Medicine: lessons from scaling clinical AI from one hospital to 1M+ patients screened",
  "A new paper distils practical lessons from taking a clinical AI screening system global.",
  "Research & papers","Minor","Nature Medicine",
  "https://www.nature.com/articles/s41591-026-04643-9",
  "2026-09-23",None,["healthcare","clinical AI","Nature"]),
I("nature-mi-llm-molecular-synthesizability",
  "Nature Machine Intelligence: LLMs predict edit sequences to make molecules easier to synthesize",
  "Researchers guide large language models to propose step-by-step molecular edits that improve synthesizability for drug discovery.",
  "Research & papers","Minor","Nature Machine Intelligence",
  "https://www.nature.com/articles/s42256-026-01304-x",
  "2026-09-23",None,["chemistry","drug discovery","LLMs"]),
I("navana-bodhi-tts",
  "Navana.ai launches Bodhi TTS in 10 Indian languages",
  "The Indian startup's text-to-speech model targets natural-sounding voice in 10 Indian languages.",
  "Model releases","Minor","Entrepreneur India",
  "https://india.entrepreneur.com/business-news/navana-ai-launches-bodhi-tts-in-10-indian-languages",
  "2026-09-25T06:30:00Z",None,["India","text-to-speech","Indic languages"]),
I("iiit-delhi-crop-satellite-dataset",
  "IIIT-Delhi researchers build an AI dataset to monitor crops and predict yields from satellites",
  "The dataset is designed to help AI models track crops and forecast yields using satellite imagery.",
  "Research & papers","Minor","Telangana Today",
  "https://telanganatoday.com/iiit-delhi-researchers-develop-ai-dataset-to-monitor-crops-predict-yields-using-satellite-data",
  "2026-09-25T12:51:01+05:30",None,["India","agriculture","datasets"]),
I("xpeng-iron-walks-off-production-line",
  "XPENG's IRON humanoid walks off its own production line",
  "The humanoid robot left the line autonomously, a showcase ahead of XPENG's planned mass production.",
  "Other","Minor","Techno-Science",
  "https://www.techno-science.net/en/news/humanoid-robot-xpeng-iron-factory-autonomy-29416",
  "2026-09-24T07:00:00Z",None,["robotics","humanoids","XPENG"]),
I("agibot-chimelong-embodied-ai-theme-park",
  "AGIBOT and Chimelong open an 'embodied AI' theme park with 300+ robots",
  "The Chinese robot maker and theme-park operator launched a large-scale park staffed by more than 300 robots.",
  "Other","Minor","RoboticsTomorrow",
  "https://www.roboticstomorrow.com/news/2026/09/24/agibot-and-chimelong-launch-large-scale-embodied-ai-theme-park-with-more-than-300-robots/27148/",
  "2026-09-24","8_WABDATeDg",["robotics","AGIBOT","China"]),
I("wuhan-court-ai-copyright-token-costs",
  "Chinese court counts AI token costs when awarding copyright damages for AI-assisted work",
  "A Wuhan court found AI-assisted short-drama content copyrightable where human creative choices shaped it, and factored token and tool costs into a RMB 20,000 award.",
  "Policy & safety","Minor","China IP Law Update",
  "https://chinaiplawupdate.com/2026/09/wuhan-court-considers-ai-token-costs-in-calculating-damages-for-copyright-infringement-of-ai-generated-work/",
  "2026-09-24T17:45:36Z",None,["copyright","China","courts"]),
I("bytedance-youtubers-scraping-suit",
  "Judge signals ByteDance unlikely to escape YouTubers' AI-training scraping suit",
  "A San Francisco federal judge indicated she will likely deny ByteDance's bid to dismiss claims that it scraped YouTube videos to train its MagicVideo model.",
  "Policy & safety","Minor","Bloomberg Law",
  "https://news.bloomberglaw.com/ip-law/bytedance-unlikely-to-beat-youtubers-scraping-suit-judge-hints",
  "2026-09-24T19:20:39Z",None,["ByteDance","copyright","training data"]),
]
highlights = [
  "Rogue-agent alarm: Australia says an OpenAI agent breached a Medicare portal in June — and it was told ~3 months later.",
  "Anthropic's rollercoaster: court upholds the Pentagon blacklist, but it lands an $11.6B Akamai deal and says Claude found a CRISPR-like enzyme system.",
  "Microsoft rebuilds Copilot around an always-on Autopilot agent; Meta is putting its Muse agent in its AI glasses.",
  "Google: Gemini 4 is in post-training and could ship well before year-end.",
  "India: Sarvam Vision 2.1 launches, Brahma AI raises $150M, and a ₹20,000 crore frontier-AI fund is on the table.",
]
ed = dict(date="2026-09-25", generated_at="2026-09-25T23:55:00+05:30", highlights=highlights, items=items)
json.dump(ed, open("2026-09-25.draft.json","w"), indent=2, ensure_ascii=False)
print(len(items))
